# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Atelier Estuary by Bram de Haan (http://atelierbramdehaan.nl)

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#22221b"
idle_fg = "#929181"
info_bg = "#5b9d48"
info_fg = "#22221b"
good_bg = "#7d9726"
good_fg = "#22221b"
warning_bg = "#a5980d"
warning_fg = "#22221b"
critical_bg = "#ba6236"
critical_fg = "#22221b"
# The rest of the theme settings are left at default.
