# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# IR Black by Timothée Poisot (http://timotheepoisot.fr)

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#000000"
idle_fg = "#b5b3aa"
info_bg = "#c6c5fe"
info_fg = "#000000"
good_bg = "#a8ff60"
good_fg = "#000000"
warning_bg = "#ffffb6"
warning_fg = "#000000"
critical_bg = "#ff6c60"
critical_fg = "#000000"
# The rest of the theme settings are left at default.
