# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Classic Dark by Jason Heeris (http://heeris.id.au)

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#151515"
idle_fg = "#D0D0D0"
info_bg = "#75B5AA"
info_fg = "#151515"
good_bg = "#90A959"
good_fg = "#151515"
warning_bg = "#F4BF75"
warning_fg = "#151515"
critical_bg = "#AC4142"
critical_fg = "#151515"
# The rest of the theme settings are left at default.
