# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Isotope by Jan T. Sott

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#000000"
idle_fg = "#d0d0d0"
info_bg = "#00ffff"
info_fg = "#000000"
good_bg = "#33ff00"
good_fg = "#000000"
warning_bg = "#ff0099"
warning_fg = "#000000"
critical_bg = "#ff0000"
critical_fg = "#000000"
# The rest of the theme settings are left at default.
