# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Brush Trees by Abraham White &lt;abelincoln.white@gmail.com&gt;

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#E3EFEF"
idle_fg = "#6D828E"
info_bg = "#86b3b3"
info_fg = "#E3EFEF"
good_bg = "#87b386"
good_fg = "#E3EFEF"
warning_bg = "#aab386"
warning_fg = "#E3EFEF"
critical_bg = "#b38686"
critical_fg = "#E3EFEF"
# The rest of the theme settings are left at default.
