# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Solarized Dark by Ethan Schoonover (http://ethanschoonover.com/solarized)

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#002b36"
idle_fg = "#93a1a1"
info_bg = "#2aa198"
info_fg = "#002b36"
good_bg = "#859900"
good_fg = "#002b36"
warning_bg = "#b58900"
warning_fg = "#002b36"
critical_bg = "#dc322f"
critical_fg = "#002b36"
# The rest of the theme settings are left at default.
