# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Atelier Seaside by Bram de Haan (http://atelierbramdehaan.nl)

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#131513"
idle_fg = "#8ca68c"
info_bg = "#1999b3"
info_fg = "#131513"
good_bg = "#29a329"
good_fg = "#131513"
warning_bg = "#98981b"
warning_fg = "#131513"
critical_bg = "#e6193c"
critical_fg = "#131513"
# The rest of the theme settings are left at default.
