# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Atelier Forest by Bram de Haan (http://atelierbramdehaan.nl)

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#1b1918"
idle_fg = "#a8a19f"
info_bg = "#3d97b8"
info_fg = "#1b1918"
good_bg = "#7b9726"
good_fg = "#1b1918"
warning_bg = "#c38418"
warning_fg = "#1b1918"
critical_bg = "#f22c40"
critical_fg = "#1b1918"
# The rest of the theme settings are left at default.
